In [1]:
import numpy as np 
import pandas as pd 
import os 

path = os.getcwd().replace('notebooks','')
path

'/home/davi/Documentos/Github/mestrado-ppgee/'

In [6]:
c1 = pd.DataFrame(
    data=np.load(path+'data/emg_train_seizure.npy'),
    columns=['path','inicio','fim','tipo','freq','tempo','montage']
)

c2 = pd.DataFrame(
    data=np.load(path+'data/emg_train_n_seizure.npy'),
    columns=['path','freq','tempo','montage']

)

In [10]:
# Frequência


print(np.unique(c1['freq'],return_counts=True))
print(np.unique(c2['freq'],return_counts=True))


(array([250, 256, 512, 1000], dtype=object), array([190, 448,  16,   2]))
(array([250, 256, 512, 1000], dtype=object), array([187, 759,  72,   2]))


In [12]:
# Tipo

np.unique(c1[c1['freq']==256].loc[:,'tipo'],return_counts=True)

(array(['CPSZ', 'FNSZ', 'GNSZ', 'TNSZ'], dtype=object),
 array([ 66, 251, 114,  17]))

In [19]:
data = c1[(c1['freq']==256) & (c1['tipo']=='GNSZ')]
data.index = np.arange(len(data))
data

path   inicio      fim  \
0    train/01_tcp_ar/044/00004456/s015_2014_06_19/0...  325.023  353.969   
1    train/01_tcp_ar/044/00004456/s015_2014_06_19/0...  454.129  470.121   
2    train/01_tcp_ar/044/00004456/s015_2014_06_19/0...  487.027  501.066   
3    train/01_tcp_ar/044/00004456/s015_2014_06_19/0...  523.156  550.106   
4    train/01_tcp_ar/044/00004456/s015_2014_06_19/0...  694.223  710.082   
..                                                 ...      ...      ...   
109  train/03_tcp_ar_a/070/00007032/s007_2011_02_10...  494.004      600   
110  train/03_tcp_ar_a/091/00009162/s002_2012_04_09...   27.832       60   
111  train/03_tcp_ar_a/091/00009162/s002_2012_04_09...  509.945  527.484   
112  train/03_tcp_ar_a/119/00011999/s007_2014_11_09...  466.269  541.203   
113  train/03_tcp_ar_a/119/00011999/s007_2014_11_09...  496.168  567.918   

     tipo freq tempo                                            montage  
0    GNSZ  256  1113  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
1    GNSZ  256  1113  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
2    GNSZ  256  1113  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
3    GNSZ  256  1113  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
4    GNSZ  256  1113  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
..    ...  ...   ...                                                ...  
109  GNSZ  256   601  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
110  GNSZ  256  1075  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
111  GNSZ  256  1075  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
112  GNSZ  256  1676  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  
113  GNSZ  256  1212  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...  

[114 rows x 7 columns]

In [20]:
np.save('emg_gnsz_train.npy',data)