In [1]:
import numpy as np 
import pandas as pd 
import os 

path = os.getcwd().replace('notebooks','')
path

'/home/davi/Documentos/Github/mestrado-ppgee/'

In [6]:
c1 = pd.DataFrame(
    data=np.load(path+'data/emg_train_seizure.npy'),
    columns=['path','inicio','fim','tipo','freq','tempo','montage']
)

c2 = pd.DataFrame(
    data=np.load(path+'data/emg_train_n_seizure.npy'),
    columns=['path','freq','tempo','montage']

)

In [10]:
# Frequência


print(np.unique(c1['freq'],return_counts=True))
print(np.unique(c2['freq'],return_counts=True))


(array([250, 256, 512, 1000], dtype=object), array([190, 448,  16,   2]))
(array([250, 256, 512, 1000], dtype=object), array([187, 759,  72,   2]))


In [12]:
# Tipo

np.unique(c1[c1['freq']==256].loc[:,'tipo'],return_counts=True)

(array(['CPSZ', 'FNSZ', 'GNSZ', 'TNSZ'], dtype=object),
 array([ 66, 251, 114,  17]))