# Definindo Montagem de EEG

In [3]:
import numpy as np 
import pandas as pd 
import os 

path = os.getcwd().replace('notebooks','')
path

'/home/davi/Documentos/Github/mestrado-ppgee/'

In [25]:
c1 = pd.DataFrame(
    data=np.load(path+"data/train_seizure.npy"),
    columns=['path','inicio','fim','tipo','freq','tempo','montage'])

c2 = pd.DataFrame(
    data=np.load(path+"data/train_n_seizure.npy"),
    columns=['path','freq','tempo','montage'])

print(len(c1),len(c2))

2370 3730


In [24]:
# Frequencia amostral

print(np.unique(c1['freq'],return_counts=True))
print(np.unique(c2['freq'],return_counts=True))


(array([250, 256, 400, 512, 1000], dtype=object), array([ 825, 1217,  276,   16,   36]))
(array([250, 256, 400, 512, 1000], dtype=object), array([ 687, 2522,  400,   82,   39]))


In [31]:
# Tipo de crise

np.unique(c1[c1['freq']==256].loc[:,'tipo'],return_counts=True)



(array(['CPSZ', 'FNSZ', 'GNSZ', 'SPSZ', 'TCSZ', 'TNSZ'], dtype=object),
 array([ 90, 883, 218,   8,   1,  17]))