In [1]:
import numpy as np
import pandas as pd 
sys.path.append('/')
# from functions.support import edfArray
# from functions.features import FFT
# from functions.classifiers import Classifiers 

In [3]:
n = pd.DataFrame(data=np.load('/home/davi/Github/mestrado-ppgee/data/train_n_seizure.npy'),columns=['path','freq','time','montage','type'])

w = pd.DataFrame(data=np.load('/home/davi/Github/mestrado-ppgee/data/train_seizure.npy'),columns=['path','start','end','event','freq','time','montage','type'])

In [5]:

ecg = ['ECG EKG-REF' ,'EEG EKG-LE' ,'EEG EKG-REF' ,'EEG EKG1-REF']

ln = []
for i in list(n.montage):
    cont = 0
    for ii in ecg:
        cont+=1
    if cont>0:   
        ln.append(1)
    else:
        ln.append(0)

lw = []
for i in list(w.montage):
    cont = 0
    for ii in ecg:
        cont+=1
    if cont>0:   
        lw.append(1)
    else:
        lw.append(0)
n['ecg'] = ln 
w['ecg'] = lw 


In [7]:
l1 = []
for i in list(n.montage):
    if 'EMG-REF' in i:
        l1.append(1)
    else:
        l1.append(0)

l2 = []
for i in list(w.montage):
    if 'EMG-REF' in i:
        l2.append(1)
    else:
        l2.append(0)

n['emg'] = l1 
w['emg'] = l2 

In [10]:
w.columns

Index(['path', 'start', 'end', 'event', 'freq', 'time', 'montage', 'type',
       'ecg', 'emg'],
      dtype='object')

In [18]:
print(w.query('ecg==1 & emg==1').shape)
print(n.query('ecg==1 & emg==1').shape)

(114, 10)
(1020, 7)


In [19]:
print('FREQ')
print(np.unique(w.freq,return_counts=True))
print(np.unique(n.freq,return_counts=True))

# FREQ = 256

FREQ
(array([256], dtype=object), array([218]))
(array([250, 256, 400, 512, 1000], dtype=object), array([ 687, 2522,  400,   82,   39]))


In [20]:
x1 = w.query('ecg==1 & emg==1 & freq==256')
x2 = n.query('ecg==1 & emg==1 & freq==256')

print(x1.shape)
print(x2.shape)


(114, 10)
(759, 7)


In [21]:
np.unique(x1.event,return_counts=True)

(array(['GNSZ'], dtype=object), array([114]))

In [25]:
print(np.unique(x1.type,return_counts=True))
print(np.unique(x2.type,return_counts=True))



(array(['01_tcp_ar', '03_tcp_ar'], dtype=object), array([93, 21]))
(array(['01_tcp_ar', '03_tcp_ar'], dtype=object), array([587, 172]))


In [30]:
x1 = x1[x1['type']=='01_tcp_ar']
x2 = x2[x2['type']=='01_tcp_ar']

print(x1.shape)
print(x2.shape)


(93, 10)
(587, 7)


In [32]:
x1.to_pickle('all_sign_w.pkl')
x2.to_pickle('all_sign_n.pkl')


In [23]:
# print('FREQ')
# print(np.unique(x1.time,return_counts=True))
# print(np.unique(x2.time,return_counts=True))

# # FREQ = 256

FREQ
(array([184, 263, 287, 300, 601, 631, 637, 638, 656, 659, 791, 846, 951,
       991, 1011, 1075, 1113, 1212, 1274, 1276, 1622, 1676, 2137, 2411],
      dtype=object), array([ 1,  1,  1,  7, 16,  1,  1,  1,  2,  2,  1,  1,  6,  1,  5,  2,  5,
        1, 43,  2, 11,  1,  1,  1]))
(array([11, 15, 19, 20, 21, 22, 25, 26, 30, 31, 32, 38, 39, 41, 42, 44, 47,
       48, 49, 51, 62, 63, 67, 68, 71, 77, 79, 80, 83, 86, 94, 97, 100,
       105, 111, 113, 118, 131, 134, 136, 137, 144, 153, 155, 166, 172,
       176, 188, 190, 197, 206, 208, 220, 222, 230, 233, 235, 236, 238,
       241, 242, 262, 264, 281, 290, 300, 301, 302, 303, 306, 310, 311,
       312, 322, 331, 333, 334, 343, 353, 358, 369, 370, 371, 374, 380,
       381, 382, 386, 392, 395, 399, 401, 414, 416, 422, 450, 452, 474,
       476, 513, 514, 521, 534, 544, 554, 557, 572, 591, 595, 601, 603,
       604, 611, 613, 622, 626, 633, 658, 661, 667, 671, 685, 695, 706,
       709, 711, 719, 721, 727, 733, 740, 742, 752, 757, 758, 76

In [24]:
# print('FREQ')
# print(np.unique(ecg_w.freq,return_counts=True))
# print(np.unique(ecg_n.freq,return_counts=True))

# # FREQ = 256

path    start      end  \
0     train/01_tcp_ar/004/00000492/s003_2003_07_18/0...   6.2825  35.8875   
1     train/01_tcp_ar/004/00000492/s003_2003_07_18/0...  33.1425       53   
2     train/01_tcp_ar/004/00000492/s003_2003_07_18/0...   9.7925   29.125   
3     train/01_tcp_ar/004/00000492/s003_2003_07_18/0...  10.2775  35.7775   
4     train/01_tcp_ar/004/00000492/s003_2003_07_18/0...  102.252   142.98   
...                                                 ...      ...      ...   
2365  train/03_tcp_ar_a/131/00013145/s001_2015_08_31...   3.8594  44.4648   
2366  train/03_tcp_ar_a/131/00013145/s002_2015_08_31...  301.598   376.16   
2367  train/03_tcp_ar_a/131/00013145/s003_2015_09_01...  316.262  399.719   
2368  train/03_tcp_ar_a/131/00013145/s003_2015_09_01...  300.559  385.059   
2369  train/03_tcp_ar_a/131/00013145/s003_2015_09_01...   302.41  393.488   

     event freq time                                            montage  \
0     GNSZ  400  165  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   
1     GNSZ  400  184  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   
2     GNSZ  400  129  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   
3     GNSZ  400  339  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   
4     GNSZ  400  339  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   
...    ...  ...  ...                                                ...   
2365  FNSZ  256   50  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   
2366  FNSZ  256  702  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   
2367  FNSZ  256  765  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   
2368  FNSZ  256  691  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   
2369  FNSZ  256  693  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...   

           type  
0     01_tcp_ar  
1     01_tcp_ar  
2     01_tcp_ar  
3     01_tcp_ar  
4     01_tcp_ar  
...         ...  
2365  03_tcp_ar  
2366  03_tcp_ar  
2367  03_tcp_ar  
2368  03_tcp_ar  
2369  03_tcp_ar  

[2370 rows x 8 columns]