# Analise ECG 1

In [12]:
import numpy as np 
import pandas as pd 

# Sem crise
x1 = pd.DataFrame(
    data=np.load('/home/davi/Documentos/Github/mestrado-ppgee/data/ecg_train_n_seizure.npy'),
    columns=['path','freq','time','montage'])

# Com Crise
x2 = pd.DataFrame(
    data=np.load('/home/davi/Documentos/Github/mestrado-ppgee/data/ecg_train_seizure.npy'),
    columns=['path','inicio','fim','tipo','freq','time','montage'])

print(x1.shape[0],x2.shape[0])

3395 2129


In [17]:
print(np.unique(x2['freq'],return_counts=True))

print(np.unique(x1['freq'],return_counts=True))


(array([250, 256, 400, 512, 1000], dtype=object), array([ 825, 1217,   35,   16,   36]))
(array([250, 256, 400, 512, 1000], dtype=object), array([ 687, 2522,   65,   82,   39]))


In [28]:
np.unique(x2[x2['freq']==256].loc[:,'tipo'],return_counts=True)

(array(['CPSZ', 'FNSZ', 'GNSZ', 'SPSZ', 'TCSZ', 'TNSZ'], dtype=object),
 array([ 90, 883, 218,   8,   1,  17]))